name: Enforce Commit Message Format

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit messages
        uses: actions/github-script@v7
        with:
          script: |
            const pattern = /^\[solution:[a-zA-Z0-9_-]+\]$/;  // Dynamic solution name
            const prNumber = context.payload.pull_request.number;

            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            let errors = [];

            for (const commit of commits.data) {
              const msg = commit.commit.message.split('\n')[0]; // Only subject line of the commit message
              if (!pattern.test(msg)) {
                errors.push(`❌ Invalid commit: "${msg}" by ${commit.commit.author.name}`);
              }
            }

            if (errors.length > 0) {
              core.setFailed(`Some commits do not meet the required format:\n${errors.join('\n')}`);
            } else {
              console.log("✅ All commit messages are valid.");
            }
